### Import Libraries

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

### Load Dataset

In [2]:
df = pd.read_csv("flight.csv")
df

,MEMBER_NO,FFP_DATE,FIRST_FLIGHT_DATE,GENDER,FFP_TIER,WORK_CITY,WORK_PROVINCE,WORK_COUNTRY,AGE,LOAD_TIME,...,SUM_YR_2,SEG_KM_SUM,LAST_FLIGHT_DATE,LAST_TO_END,AVG_INTERVAL,MAX_INTERVAL,EXCHANGE_COUNT,avg_discount,Points_Sum,Point_NotFlight
0,54993,11/2/2006,12/24/2008,Male,6,.,beijing,CN,31.0,3/31/2014,...,234188.0,580717,3/31/2014,1,3.483254,18,34,0.961639,619760,50
1,28065,2/19/2007,8/3/2007,Male,6,NaN,beijing,CN,42.0,3/31/2014,...,167434.0,293678,3/25/2014,7,5.194245,17,29,1.252314,415768,33
2,55106,2/1/2007,8/30/2007,Male,6,.,beijing,CN,40.0,3/31/2014,...,164982.0,283712,3/21/2014,11,5.298507,18,20,1.254676,406361,26
3,21189,8/22/2008,8/23/2008,Male,5,Los Angeles,CA,US,64.0,3/31/2014,...,125500.0,281336,12/26/2013,97,27.863636,73,11,1.090870,372204,12
4,39546,4/10/2009,4/15/2009,Male,6,guiyang,guizhou,CN,48.0,3/31/2014,...,130702.0,309928,3/27/2014,5,4.788079,47,27,0.970658,338813,39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62983,18375,5/20/2011,6/5/2013,Female,4,guangzhou,guangdong,CN,25.0,3/31/2014,...,0.0,1134,6/9/2013,297,4.000000,4,1,0.000000,12318,22
62984,36041,3/8/2010,9/14/2013,Male,4,foshan,guangdong,CN,38.0,3/31/2014,...,0.0,8016,1/3/2014,89,37.000000,60,14,0.000000,106972,43
62985,45690,3/30/2006,12/2/2006,Female,4,guangzhou,guangdong,CN,43.0,3/31/2014,...,0.0,2594,3/3/2014,29,166.000000,166,0,0.000000,0,0
62986,61027,2/6/2013,2/14/2013,Female,4,guangzhou,guangdong,CN,36.0,3/31/2014,...,0.0,3934,2/26/2013,400,12.000000,12,0,0.000000,0,0
62987,61340,2/17/2013,2/17/2013,Female,4,shanghai,.,CN,29.0,3/31/2014,...,0.0,4222,2/23/2013,403,6.000000,6,0,0.000000,0,0

In [3]:
df.head()

,MEMBER_NO,FFP_DATE,FIRST_FLIGHT_DATE,GENDER,FFP_TIER,WORK_CITY,WORK_PROVINCE,WORK_COUNTRY,AGE,LOAD_TIME,...,SUM_YR_2,SEG_KM_SUM,LAST_FLIGHT_DATE,LAST_TO_END,AVG_INTERVAL,MAX_INTERVAL,EXCHANGE_COUNT,avg_discount,Points_Sum,Point_NotFlight
0,54993,11/2/2006,12/24/2008,Male,6,.,beijing,CN,31.0,3/31/2014,...,234188.0,580717,3/31/2014,1,3.483254,18,34,0.961639,619760,50
1,28065,2/19/2007,8/3/2007,Male,6,NaN,beijing,CN,42.0,3/31/2014,...,167434.0,293678,3/25/2014,7,5.194245,17,29,1.252314,415768,33
2,55106,2/1/2007,8/30/2007,Male,6,.,beijing,CN,40.0,3/31/2014,...,164982.0,283712,3/21/2014,11,5.298507,18,20,1.254676,406361,26
3,21189,8/22/2008,8/23/2008,Male,5,Los Angeles,CA,US,64.0,3/31/2014,...,125500.0,281336,12/26/2013,97,27.863636,73,11,1.090870,372204,12
4,39546,4/10/2009,4/15/2009,Male,6,guiyang,guizhou,CN,48.0,3/31/2014,...,130702.0,309928,3/27/2014,5,4.788079,47,27,0.970658,338813,39

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62988 entries, 0 to 62987
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   MEMBER_NO          62988 non-null  int64
 1   FFP_DATE           62988 non-null  object
 2   FIRST_FLIGHT_DATE  62988 non-null  object
 3   GENDER             62985 non-null  object
 4   FFP_TIER           62988 non-null  int64
 5   WORK_CITY          60719 non-null  object
 6   WORK_PROVINCE      59740 non-null  object
 7   WORK_COUNTRY       62962 non-null  object
 8   AGE                62568 non-null  float64
 9   LOAD_TIME          62988 non-null  object
 10  FLIGHT_COUNT       62988 non-null  int64
 11  BP_SUM             62988 non-null  int64
 12  SUM_YR_1           62437 non-null  float64
 13  SUM_YR_2           62850 non-null  float64
 14  SEG_KM_SUM         62988 non-null  int64
 15  LAST_FLIGHT_DATE   62988 non-null  object
 16  LAST_TO_END        62988 non-null  int64
 17  AVG_INTERVAL       62988 non-null  float64
 18  MAX_INTERVAL       62988 non-null  int64
 19  EXCHANGE_COUNT     62988 non-null  int64
 20  avg_discount       62988 non-null  float64
 21  Points_Sum         62988 non-null  int64
 22  Point_NotFlight    62988 non-null  int64
dtypes: float64(5), int64(10), object(8)
memory usage: 11.1+ MB

In [5]:
df.describe(include='all')

,MEMBER_NO,FFP_DATE,FIRST_FLIGHT_DATE,GENDER,FFP_TIER,WORK_CITY,WORK_PROVINCE,WORK_COUNTRY,AGE,LOAD_TIME,...,SUM_YR_2,SEG_KM_SUM,LAST_FLIGHT_DATE,LAST_TO_END,AVG_INTERVAL,MAX_INTERVAL,EXCHANGE_COUNT,avg_discount,Points_Sum,Point_NotFlight
count,62988.000000,62988,62988,62985,62988.000000,60719,59740,62962,62568.000000,62988,...,62850.000000,62988.000000,62988,62988.000000,62988.000000,62988.000000,62988.000000,62988.000000,62988.0000,62988.000000
unique,NaN,3068,3406,2,NaN,3234,1165,118,NaN,1,...,NaN,NaN,731,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,1/13/2011,2/16/2013,Male,NaN,guangzhou,guangdong,CN,NaN,3/31/2014,...,NaN,NaN,3/31/2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,184,96,48134,NaN,9386,17509,57748,NaN,62988,...,NaN,NaN,959,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,31494.500000,NaN,NaN,NaN,4.102162,NaN,NaN,NaN,42.476346,NaN,...,5604.026014,17123.878691,NaN,176.120102,67.749788,166.033895,0.319775,0.721558,12545.7771,2.728155
std,18183.213715,NaN,NaN,NaN,0.373856,NaN,NaN,NaN,9.885915,NaN,...,8703.364247,20960.844623,NaN,183.822223,77.517866,123.397180,1.136004,0.185427,20507.8167,7.364164
min,1.000000,NaN,NaN,NaN,4.000000,NaN,NaN,NaN,6.000000,NaN,...,0.000000,368.000000,NaN,1.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000
25%,15747.750000,NaN,NaN,NaN,4.000000,NaN,NaN,NaN,35.000000,NaN,...,780.000000,4747.000000,NaN,29.000000,23.370370,79.000000,0.000000,0.611997,2775.0000,0.000000
50%,31494.500000,NaN,NaN,NaN,4.000000,NaN,NaN,NaN,41.000000,NaN,...,2773.000000,9994.000000,NaN,108.000000,44.666667,143.000000,0.000000,0.711856,6328.5000,0.000000
75%,47241.250000,NaN,NaN,NaN,4.000000,NaN,NaN,NaN,48.000000,NaN,...,6845.750000,21271.250000,NaN,268.000000,82.000000,228.000000,0.000000,0.809476,14302.5000,1.000000
max,62988.000000,NaN,NaN,NaN,6.000000,NaN,NaN,NaN,110.000000,NaN,...,234188.000000,580717.000000,NaN,731.000000,728.000000,728.000000,46.000000,1.500000,985572.0000,140.000000

### Preprocessing

In [6]:
df.isnull()

,MEMBER_NO,FFP_DATE,FIRST_FLIGHT_DATE,GENDER,FFP_TIER,WORK_CITY,WORK_PROVINCE,WORK_COUNTRY,AGE,LOAD_TIME,...,SUM_YR_2,SEG_KM_SUM,LAST_FLIGHT_DATE,LAST_TO_END,AVG_INTERVAL,MAX_INTERVAL,EXCHANGE_COUNT,avg_discount,Points_Sum,Point_NotFlight
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62983,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
62984,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
62985,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
62986,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
62987,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [7]:
df.isnull().sum()

MEMBER_NO               0
FFP_DATE                0
FIRST_FLIGHT_DATE       0
GENDER                  3
FFP_TIER                0
WORK_CITY            2269
WORK_PROVINCE        3248
WORK_COUNTRY           26
AGE                   420
LOAD_TIME               0
FLIGHT_COUNT            0
BP_SUM                  0
SUM_YR_1              551
SUM_YR_2              138
SEG_KM_SUM              0
LAST_FLIGHT_DATE        0
LAST_TO_END             0
AVG_INTERVAL            0
MAX_INTERVAL            0
EXCHANGE_COUNT          0
avg_discount            0
Points_Sum              0
Point_NotFlight         0
dtype: int64

In [8]:
df.dtypes

MEMBER_NO              int64
FFP_DATE              object
FIRST_FLIGHT_DATE     object
GENDER                object
FFP_TIER               int64
WORK_CITY             object
WORK_PROVINCE         object
WORK_COUNTRY          object
AGE                  float64
LOAD_TIME             object
FLIGHT_COUNT           int64
BP_SUM                 int64
SUM_YR_1             float64
SUM_YR_2             float64
SEG_KM_SUM             int64
LAST_FLIGHT_DATE      object
LAST_TO_END            int64
AVG_INTERVAL         float64
MAX_INTERVAL           int64
EXCHANGE_COUNT         int64
avg_discount         float64
Points_Sum             int64
Point_NotFlight        int64
dtype: object

In [9]:
def QuanQual(df):
    quan = []
    qual = []
    for columnName in df.columns:
        #print(columnName)
        if (df[columnName].dtype=='O'):
            #print ("Qual")
            qual.append (columnName)
        else:
            #print("quan")
            quan.append (columnName)
    return quan,qual

In [10]:
QuanQual(df)

(['MEMBER_NO',
  'FFP_TIER',
  'AGE',
  'FLIGHT_COUNT',
  'BP_SUM',
  'SUM_YR_1',
  'SUM_YR_2',
  'SEG_KM_SUM',
  'LAST_TO_END',
  'AVG_INTERVAL',
  'MAX_INTERVAL',
  'EXCHANGE_COUNT',
  'avg_discount',
  'Points_Sum',
  'Point_NotFlight'],
 ['FFP_DATE',
  'FIRST_FLIGHT_DATE',
  'GENDER',
  'WORK_CITY',
  'WORK_PROVINCE',
  'WORK_COUNTRY',
  'LOAD_TIME',
  'LAST_FLIGHT_DATE'])

In [11]:
quan,qual = QuanQual(df)

In [12]:
quan

['MEMBER_NO',
 'FFP_TIER',
 'AGE',
 'FLIGHT_COUNT',
 'BP_SUM',
 'SUM_YR_1',
 'SUM_YR_2',
 'SEG_KM_SUM',
 'LAST_TO_END',
 'AVG_INTERVAL',
 'MAX_INTERVAL',
 'EXCHANGE_COUNT',
 'avg_discount',
 'Points_Sum',
 'Point_NotFlight']

In [13]:
qual

['FFP_DATE',
 'FIRST_FLIGHT_DATE',
 'GENDER',
 'WORK_CITY',
 'WORK_PROVINCE',
 'WORK_COUNTRY',
 'LOAD_TIME',
 'LAST_FLIGHT_DATE']

In [14]:
c_df= pd.get_dummies(df, drop_first=True, dtype=int)

In [15]:
c_df

,MEMBER_NO,FFP_TIER,AGE,FLIGHT_COUNT,BP_SUM,SUM_YR_1,SUM_YR_2,SEG_KM_SUM,LAST_TO_END,AVG_INTERVAL,...,LAST_FLIGHT_DATE_9/5/2012,LAST_FLIGHT_DATE_9/5/2013,LAST_FLIGHT_DATE_9/6/2012,LAST_FLIGHT_DATE_9/6/2013,LAST_FLIGHT_DATE_9/7/2012,LAST_FLIGHT_DATE_9/7/2013,LAST_FLIGHT_DATE_9/8/2012,LAST_FLIGHT_DATE_9/8/2013,LAST_FLIGHT_DATE_9/9/2012,LAST_FLIGHT_DATE_9/9/2013
0,54993,6,31.0,210,505308,239560.0,234188.0,580717,1,3.483254,...,0,0,0,0,0,0,0,0,0,0
1,28065,6,42.0,140,362480,171483.0,167434.0,293678,7,5.194245,...,0,0,0,0,0,0,0,0,0,0
2,55106,6,40.0,135,351159,163618.0,164982.0,283712,11,5.298507,...,0,0,0,0,0,0,0,0,0,0
3,21189,5,64.0,23,337314,116350.0,125500.0,281336,97,27.863636,...,0,0,0,0,0,0,0,0,0,0
4,39546,6,48.0,152,273844,124560.0,130702.0,309928,5,4.788079,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62983,18375,4,25.0,2,0,0.0,0.0,1134,297,4.000000,...,0,0,0,0,0,0,0,0,0,0
62984,36041,4,38.0,4,0,0.0,0.0,8016,89,37.000000,...,0,0,0,0,0,0,0,0,0,0
62985,45690,4,43.0,2,0,0.0,0.0,2594,29,166.000000,...,0,0,0,0,0,0,0,0,0,0
62986,61027,4,36.0,2,0,0.0,0.0,3934,400,12.000000,...,0,0,0,0,0,0,0,0,0,0
62987,61340,4,29.0,2,0,NaN,0.0,4222,403,6.000000,...,0,0,0,0,0,0,0,0,0,0

In [16]:
df1 = pd.DataFrame(df,columns = quan)

In [17]:
from sklearn.impute import SimpleImputer

# Suppose df is your dataset
quan, qual = QuanQual(df)

# Fill categorical columns with mode
imp_cat = SimpleImputer(strategy='most_frequent')
df[qual] = imp_cat.fit_transform(df[qual])

# Fill numerical columns with mean
imp_num = SimpleImputer(strategy='mean')
df[quan] = imp_num.fit_transform(df[quan])

# Verify no missing values
print(df.isnull().sum())

MEMBER_NO            0
FFP_DATE             0
FIRST_FLIGHT_DATE    0
GENDER               0
FFP_TIER             0
WORK_CITY            0
WORK_PROVINCE        0
WORK_COUNTRY         0
AGE                  0
LOAD_TIME            0
FLIGHT_COUNT         0
BP_SUM               0
SUM_YR_1             0
SUM_YR_2             0
SEG_KM_SUM           0
LAST_FLIGHT_DATE     0
LAST_TO_END          0
AVG_INTERVAL         0
MAX_INTERVAL         0
EXCHANGE_COUNT       0
avg_discount         0
Points_Sum           0
Point_NotFlight      0
dtype: int64

In [18]:
# Remove Dulplicate Records

In [19]:
df.duplicated().sum()

0

In [20]:
df.drop_duplicates(inplace=True)

In [21]:
df.to_csv('preprocessed_data_flight.csv', index=False)